---
# handlers file for teamspeak

- name: Reload systemd
  systemd:
    daemon-reload: yes

- name: Reload initd
  service:
    name: teamspeak3-server
    enabled: yes

- name: Restart TeamSpeak 3 Server
  service:
    name: teamspeak3-server
    state: restarted

- name: Prune older TeamSpeak 3 Server versions
  shell: "{{ item }}"
  args:
    executable: /bin/bash
  with_items:
    - set -o pipefail && find {{ teamspeak.home }}/teamspeak3-server_linux_amd64-* -maxdepth 0 -type d | sort | head -n-{{ teamspeak.keep }} | xargs echo rm -rf
    - set -o pipefail && find {{ teamspeak.home }}/teamspeak3-server_linux_amd64-*.tar.bz2 -type f | sort | head -n-{{ teamspeak.keep }} | xargs rm -f
